### ISSUE TITLE
Fail to login

### ISSUE THREAD

**Issue by PeterSchumacher** [zylopfa/acme.sh_dns_gratisdns#1]
After GratisDNS had a design upgrade, the script stopped working.

Here's a snippet from the logs,
<pre>
[tir feb 12 00:32:10 CET 2019] Gratis DNS login failed for user xxx@schumacher.dk
[tir feb 12 00:32:11 CET 2019] The top domain schumacher.dk is not registered under this gratisdns account (xxx@schumacher.dk)
[tir feb 12 00:32:11 CET 2019] Error add txt for domain:_acme-challenge.app01.schumacher.dk
[tir feb 12 00:32:11 CET 2019] Please check log file for more details: /home/peter/.acme.sh/acme.sh.log
[tir feb 12 00:32:16 CET 2019] Gratis DNS login failed for user xxx@schumacher.dk
[tir feb 12 00:32:16 CET 2019] The top domain schumacher.dk is not registered under this gratisdns account (xxx@schumacher.dk)
[tir feb 12 00:32:16 CET 2019] Error removing txt for domain:_acme-challenge.app01.schumacher.dk
[tir feb 12 00:32:16 CET 2019] Error renew app01.schumacher.dk.
</pre>

BTW, keep up the good work!

**Comment by PeterSchumacher** [comment]
Fixed the issue and created a pull request here : https://github.com/zylopfa/acme.sh_dns_gratisdns/pull/2

**Comment by dko1905** [comment]
This issue should be closed.

**Comment by zylopfa** [comment]
Closing issue, thanks to  PeterSchumacher for fix.
